### ISSUE TITLE
Create New Template C# & AJAX

### ISSUE THREAD

**Issue by SMPSLLC** [darrencauthon/csharp-sparkpost#102]
Always i get the 422 Error Message :(
This is a Model:
`    public class Templates
    {
        public Dictionary<string, object> results { get; set; }
    }`

AJAX:
`$.ajax({
                url: "/CreateTemplate",
                type: "POST",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({
                    "results": {
                        id: "my-test-1",
                        name: "my test",
                        published: true,
                        description: "my test description",
                        options: {
                            "open_tracking": true,
                            "click_tracking": true,
                            "transactional": true
                        },
                        content: {
                            "from": {
                                "email": "foo@domain.net",
                                "name": "foo"
                            },
                            "subject":"welcome back sir!",
                            "reply_to": "foo@domain.net",
                            "text": "lorem ipsum",
                            "html": "<b>lorem ipsum</b>",
                            "headers": {
                                "X-Customer-Campaign-ID": "DM_2235_TBULK_4852157_552_2016"
                            }
                        }
                    }
                }),
                async: false,
                cache: false,
                success: function (response) {
                    console.log(response);
                }
            });`

The HttpWebRequest Method:

`//results as paramater
var data = JsonConvert.SerializeObject(results);

            HttpWebRequest myHttpWebRequest = (HttpWebRequest)WebRequest.Create("https://api.sparkpost.com/api/v1/templates");
            myHttpWebRequest.Method = "POST";
            myHttpWebRequest.Headers.Add("Authorization", "2c*****************************");

            byte[] byteArray = Encoding.ASCII.GetBytes(data);

            myHttpWebRequest.ContentType = "application/x-www-form-urlencoded";
            myHttpWebRequest.ContentLength = byteArray.Length;

            Stream requestStream = myHttpWebRequest.GetRequestStream();
            requestStream.Write(byteArray, 0, byteArray.Length);
            requestStream.Close();

            HttpWebResponse myHttpWebResponse = (HttpWebResponse)myHttpWebRequest.GetResponse();

            Stream responseStream = myHttpWebResponse.GetResponseStream();

            StreamReader myStreamReader = new StreamReader(responseStream, Encoding.Default);

            string pageContent = myStreamReader.ReadToEnd();

            myStreamReader.Close();
            responseStream.Close();

            myHttpWebResponse.Close();

            return pageContent;`

Please help Me!

**Comment by darrencauthon** [comment]
This does not seem to be an issue with this library.  It looks like you are coding it by hand.  You might try the csharp channel on the SparkPost slack for help on this.
