### ISSUE TITLE
Is Alive check

### ISSUE THREAD

**Issue by Jetski5822** [darrencauthon/csharp-sparkpost#104]
Hey - Is there an Is Alive check somewhere? an end point I can ping to check to see if the service is up and kicking with the valid APIKey etc?

**Comment by Jetski5822** [comment]
Maybe a call to this endpoint https://developers.sparkpost.com/api/account would be enough

**Comment by darrencauthon** [comment]
Hmm... I like the idea, but I'm not sure how we could provide a check that would work for all.

Like this check against that endpoint, I checked the API permissions and it was on this list:

![screenshot_091416_102712_pm](https://cloud.githubusercontent.com/assets/148768/18537331/6376f15c-7aca-11e6-884d-aa94d6dd3483.jpg)

I set up an API key for production that does not allow access to Account, so an Is Alive check against it wouldn't work.

**Comment by darrencauthon** [comment]
But thinking aloud, you've given me an idea.  Why don't we had support in the library that checks the SparkPost status pages?  We couldn't use this method to check for an individual account, but we could check for the status of the overall system.  I don't know how useful that would be for users, but... that never stopped me from programming anything. :tongue:

**Comment by darrencauthon** [comment]
I still like this idea, kinda of.... but I think it would be better if people who are interested in SparkPost availability to use the SparkPost solutions for this.  

Specifically, check their status page at http://status.sparkpost.com/ and subscribe to email & text updates to any status updates.
