### ISSUE TITLE
Cannot use await client.RecipientLists.Retrieve("myList")

### ISSUE THREAD

**Issue by clashvk** [darrencauthon/csharp-sparkpost#105]
It throws up an exception on the RetrieveRecipientListsResponse class. 
`

> "Cannot implicitly convert type 'Newtonsoft.Json.Linq.JObject' to 'System.Collections.Generic.IDictionary<string,object>"

`

**Comment by darrencauthon** [comment]
Hmm... I'll take a look this weekend.  Thanks for reporting!

**Comment by darrencauthon** [comment]
![screenshot_100216_093035_pm](https://cloud.githubusercontent.com/assets/148768/19026103/7517e2ec-88e7-11e6-9991-a435c80b4fe3.jpg)

**Comment by clashvk** [comment]
Thanks darren, nuget package good to go ?

**Comment by darrencauthon** [comment]
@clashvk Just released here:  https://github.com/darrencauthon/csharp-sparkpost/releases/tag/1.9.2

Can you try it out and let me know how it works for you?

**Comment by clashvk** [comment]
I have tested it and it can retrieve the list. I can create a new list and add a recipient to it and it does show up on sparkpost, but 

> it doesnt seem to add new recipient to a retrieved list

. It shows up on the list on code. Is there a save list method to invoke ? 

```
 var to = new SparkPost.Recipient();
            to.Address.Email = "sample@sample.com";
            to.Address.Name = "Mr Sample Example";
           
var myList = await client.RecipientLists.Retrieve("My-List");
            myList.RecipientLists.Add(to);
```
