### ISSUE TITLE
Add Update method to RecipientLists.cs

### ISSUE THREAD

**Issue by clashvk** [darrencauthon/csharp-sparkpost#110]
In Reference to #105, Sparkpost has an update method for [recipientList](https://developers.sparkpost.com/api/recipient-lists.html#recipient-lists-update-put). Please add it to the RecipientLists.cs.

```
 public async Task<RetrieveRecipientListsResponse> Update ( RecipientList recipientList ) 
        {
            var request = new Request {
                Url = $"api/{client.Version}/recipient-lists/"+recipientList.Id+"_?num_rcpt_errors=3",
                Method = "PUT",
                Data = dataMapper.ToDictionary(recipientList)
            };

            
            var response = await requestSender.Send(request);

... So On
```

**Comment by darrencauthon** [comment]
That shouldn't be difficult.

I wish they had a way to make updates to the list without updating the entire list.

**Comment by clashvk** [comment]
True.

**Comment by clashvk** [comment]
Hi darren, I'm trying to add the put method .. but something's not working with the data mapper. Do you have one done in the tests ?

**Comment by darrencauthon** [comment]
@clashvk Ahhhh I'm not sure.

I looked at the code over lunch, and I think the biggest problem is that the recipient retrieve method does not return an actual RecipientList.  Instead, it returns a glob of the http response with all of the fields that belong on a RecipientList.

I'm still working on it.

**Comment by darrencauthon** [comment]
@clashvk Please check version 1.9.3; the update method should be available on nuget shortly.

Let me know if you find any issues.

https://github.com/darrencauthon/csharp-sparkpost/releases/tag/1.9.3
