### ISSUE TITLE
More Async Weirdness (Wait / await never returns)

### ISSUE THREAD

**Issue by black-orchid** [darrencauthon/csharp-sparkpost#146]
I reviewed the other thread on odd async behavior (Wait() and await that never returns), #39, and maybe my problem can be solved by just using the built-in sync functionality that is now available, but I thought I'd open this issue just in case the root cause can be discovered. I'm sending mail from a console Hangfire server that handles our background tasks. Each email is fired as an individual task, and up to five can attempt to process simultaneously. With some regularity, the emails will hang up and fail to complete indefinitely (for days). Sending them back the queue results in them processing just fine. This can happen even if only two are running at once, but I've never observed it if only one is processing at a time (could be a coincidence, though). Other times, we'll fire off 100 emails without a hitch. Here's the method:
```
public static async Task SendEmail(String sFrom, String sRecipient, String sSubject, String sBody, bool bGetCopy, bool bHTML)
        {
            SparkPost.Client client = new SparkPost.Client(System.Configuration.ConfigurationManager.AppSettings["SparkPostAPIKey"]);
            SparkPost.Transmission trans = new SparkPost.Transmission();
            SparkPost.Recipient r = new SparkPost.Recipient { Address = new SparkPost.Address { Email = sRecipient } };
            trans.Recipients.Add(r);
            trans.Content.From.Email = #####
            trans.Content.From.Name = ######
            trans.Content.Subject = sSubject;
            trans.Options.ClickTracking = false;
            trans.Options.OpenTracking = true;
            if (bHTML) trans.Content.Html = sBody;
            else trans.Content.Text = sBody;

            Console.WriteLine("About to call send for " + sRecipient);
            try { 
                SendTransmissionResponse result = await client.Transmissions.Send(trans);
                Console.WriteLine("Result: " + result.StatusCode);
            }
            catch(Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }
```

**Comment by darrencauthon** [comment]
What version of Hangfire are you using?

**Comment by black-orchid** [comment]
Hangfire 1.6.2, .Net 4.5.2.

**Comment by darrencauthon** [comment]
@black-orchid I'd recommend using the Sync mode, anyway.  I don't think that version of Hangfire supports async entirely.  

And I say this having used Hangfire a lot.  For my own safety, I don't expose the async/await features of my code for Hangfire to manage.  If the feature is asynchronous, I'll wrap it in:

```c#
Task.Wait(async() => {
    // do async stuff here
}).Wait();
```

I've never seen this happen in Hangfire, but it might be because I use the window service mode -- not the console app version of Hangfire.  From my own experiences using async, the behavior can be erratic within a console app unless it is wrapped at some level.

**Comment by darrencauthon** [comment]
I'm going to close this library because I do not think these are issues with the library.  

If you are experiencing weird behaviors, you can probably get around them by making this library go synchronous like this:

```c#
var client = new Client("");
client.CustomSettings.SendingMode = SendingModes.Sync;
```

**Comment by black-orchid** [comment]
Thanks!
