### ISSUE TITLE
SparkPost Library not works

### ISSUE THREAD

**Issue by gotorresgt18** [darrencauthon/csharp-sparkpost#169]
I had using it since 2016 and since and from July 23, 2018 to date, the class library dont works.

**Comment by Nemisys** [comment]
I just noticed emails failing to send as well.

**Comment by gotorresgt18** [comment]
I had seen this link and did what I was told there but it did not work.

https://www.sparkpost.com/docs/tech-resources/tlsv1-0-test-hostname/

But I just did what you told me and everything worked wonders, thank you very much.
