### ISSUE TITLE
Client.CustomSettings.SendingMode = SendingModes.Sync is no more working in 2.0.2

### ISSUE THREAD

**Issue by ArchSwiftpage** [darrencauthon/csharp-sparkpost#200]
I upgraded to 2.0.2,  I am getting error on this line Client.CustomSettings.SendingMode = SendingModes.Sync
SendingMode is not a property of CustomSettings. Please suggest what is code for this ifix.

**Comment by adamhathcock** [comment]
There is no more sending mode options.  Everything is Async.  

Previously, with the Sync option, it would be async then Wait to tie up the thread pool.  This has been removed.

**Comment by ArchSwiftpage** [comment]
thank for your response and clarifications!

**Comment by adamhathcock** [comment]
You don't, use async/await.  That concept has been around for a decade.  

There are ways but that is out of scope for support of this library.

**Comment by darrencauthon** [comment]
I get it, at some point, dot net devs have to understand async. Just to warn, I received SO MANY emails and messages from people who didn't understand why their emails would not send. The Sync mode was a patch to end them, which worked.

**Comment by adamhathcock** [comment]
You added Sync mode in 2016 which would make sense as `async` was still fairly new about how to use it.  6 years on, I don't think it's something that should encouraged or supported.

If people don't want to update their code, they don't need to update their nuget reference.

Not trying to be a jerk but things need to move on to make maintenance easier.

**Comment by darrencauthon** [comment]
That's cool, just giving the context and warning. Good luck!

**Comment by ArchSwiftpage** [comment]
yes, we used it in 2016, now updating all the nuget packages in our project.
Finally found a way to invoke this in sync mode. thanks for your guidence and motivation :-)

**Comment by adamhathcock** [comment]
Glad it worked out
