### ISSUE TITLE
Set up coverage reports

### ISSUE THREAD

**Issue by richleland** [darrencauthon/csharp-sparkpost#4]
We use coveralls for our client libraries.

* Configure Travis to work with coveralls
* Add coveralls badge

This library might help: https://github.com/csMACnz/coveralls.net

**Comment by darrencauthon** [comment]
I'll just find the version that works with Travis, no problem. I haven't tried building the solution on my Mac with Xamarin yet -- that'll give me a good idea of what it needs to build on Linux.

**Comment by darrencauthon** [comment]
This would be great to do... just not going to do it right now. :smile:
