### ISSUE TITLE
Provide Webhook event classes to ease callback handling

### ISSUE THREAD

**Issue by pawelpawlow** [darrencauthon/csharp-sparkpost#50]
It would be nice to have C# classes of the event data that are posted as JSON by a Webhook callback. We can then use them to deserialize the payload of a Webhook callback.

**Comment by darrencauthon** [comment]
It would be nice if someone could make simple POCOs that we could use in a MVC action, I totally agree.

Who's up for this?

**Comment by gbronzer** [comment]
Is there a reason ZA1's classes haven't been merged into the master? It's exactly what I need but I was hoping to avoid pulling and compiling a separate branch.

Thanks

**Comment by darrencauthon** [comment]
@gbronzer I just asked @ZA1 about it... if someone has used this code, I say why not?

I'm going to close this ticket as #70 is the answer to this ticket.  If it's not, we can start another solution and reference this ticket again.
