### ISSUE TITLE
How to send attachments using a stored template

### ISSUE THREAD

**Issue by stevetapley** [darrencauthon/csharp-sparkpost#91]
Hi,
I'm trying to send an email with an attachment using a template that I have stored in my SparkPost account.  I've taken a look at https://www.sparkpost.com/blog/advanced-email-templates, but its not really giving me much help, I'm afraid.

Does anyone have any sample code for how this can be done?

Thanks,
Steve

**Comment by darrencauthon** [comment]
@stevetapley I had the same issue... and... I don't think it's possible.  I do not believe SparkPost supports attachments on a template email.

You'll have to ask SparkPost why.  I did, and they gave me some reasons why, but I can't remember them.

I came back to my company with this fact, and I was able to talk them out of the attachment.  So SparkPost not supporting this actually helped us, as it forced us to question our preconceived notion that we needed an attachment.  We went with a link that would allow the user to download the attachment.  

I'll tell you, too... in my general experience, there are some differences in the behavior of SparkPost transmissions with a template id, and without.  I can't remember any specifics (other than this one), but here's my approach:

1) If a template transmission does not work like I'd expect, switch it to a transmission with NO template_id (have to set the email subject & body instead).

2)  If the feature works as a regular email, then it's probably a difference in how the template emails are processed.

3)  If the feature does not work in a regular email, then I might be doing it wrong.  Fix the issue sending the "regular" email, then verify with a template email after I get it working.

**Comment by darrencauthon** [comment]
Maybe @richleland or @aydrian have input on this?  

I'm going to close this ticket, @stevetapley.  Not because I don't want to help, but I just don't think this is a resolvable ticket.  We can still comment on it in this thread, in case someone else searches for this issue.

**Comment by darrencauthon** [comment]
@stevetapley Oh, one last thing:  Someone on SparkPost's slack channel had a potential solution for me.  It wasn't sending an attachment the "regular" way, but another way that they thought I should try.  I was going to, but by then my biz had decided not to use an attachment at all.

**Comment by stevetapley** [comment]
@darrencauthon Thanks for the insight.  I too could use a link and get them to download the attachment - its not ideal but it might have to do.   The other thing I considered was just not using a template, and building the HTML message body in code - which isn't particularly ideal either :(

Coming from Mandrill, this is an area that definitely could be improved.

Anyway, thanks for your help.  I'll ask on their slack channel as well.

**Comment by darrencauthon** [comment]
@stevetapley Let me know if anything changes. I almost wonder if this library should throw in these circumstances, as we know it's not going to work... It's just going to fail silently and more devs will be confused.

**Comment by cristoirmac** [comment]
A work around is to use a stored template, then fetch it via API, add the attachment and then send inline.  You should cache the template locally rather than fetch it for each transmission API call.  We did this in the WordPress plugin.
